name: Deploy on GCP VM lourenco

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_LOUREN_CO_IN }}" > ~/.ssh/id_ed25519
          echo "louren.co.in ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII2CTevgsxQHdubtbuxfLJDi9eVVtZr03W1LSdkm4XY5" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_ed25519
      - name: Deploy
        run: |
          ssh -T user@louren.co.in << EOF
            export PATH=/home/user/.nvm/versions/node/v23.11.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin
            pm2 stop ecommerce
            cd ~/GitRepos/playwright06-ecommerce
            git pull
            npm install
            echo "FIREBASE_PROJECT_ID=\"${{ secrets.FIREBASE_PROJECT_ID }}\"" > .env
            echo "FIREBASE_PRIVATE_KEY=\"${{ secrets.FIREBASE_PRIVATE_KEY }}\"" >> .env
            echo "FIREBASE_CLIENT_EMAIL=\"${{ secrets.FIREBASE_CLIENT_EMAIL }}\"" >> .env
            echo "FIREBASE_DATABASE_URL=\"${{ secrets.FIREBASE_DATABASE_URL }}\"" >> .env
            pm2 restart ecommerce
          EOF