name: Deploy on Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_LOUREN_CO_IN }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "Host 35.222.84.1\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config
          cat ~/.ssh/config
          cat ~/.ssh/id_ed25519
      - name: Deploy
        run: |
          ssh -T -i ~/.ssh/id_ed25519 lourenco@35.222.84.1 << EOF
            cd ~/GitRepos/playwright06-ecommerce
            echo oi > oi.txt
            git pull
            npm install
            pm2 restart ecommerce
            pm2 ls
          EOF