name: Deploy on Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_LOUREN_CO_IN }}" > ~/.ssh/id_ed25519
          echo "35.222.84.1 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICArDzAYhoe4WRAsbNAE4Y1FcrtILg3U2eNFnuDTpIze" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_ed25519
      - name: Deploy
        run: |
          ssh -T lourenco@35.222.84.1 << EOF
            cd ~/GitRepos/playwright06-ecommerce
            git pull
            npm install
            npx playwright install
            echo "FIREBASE_PROJECT_ID=\"${{ secrets.FIREBASE_PROJECT_ID }}\"\n" > .env
            echo "FIREBASE_PRIVATE_KEY=\"${{ secrets.FIREBASE_PRIVATE_KEY }}\"\n" >> .env
            echo "FIREBASE_CLIENT_EMAIL=\"${{ secrets.FIREBASE_CLIENT_EMAIL }}\"" >> .env
            pm2 restart ecommerce
          EOF